### ISSUE TITLE
Use MiB and TiB prefix in dashboard or use powers of 10 insead of 2 on limits

### ISSUE THREAD

**Issue by Delivator** [SkynetLabs/webportal-accounts-dashboard#36]
## Overview

The limtis for portal account tiers are set to numbers of powers of 2 where 1 KiB is 1024 Bytes.
But the dashboard shows limits with the prefix used on numbers of the power of 10 where 1KB is 1000 Bytes.

## Design or Proposal

Use the correct prefix in the dashboard (MiB/s, TiB etc.) or change the limits to use powers of 10.

**Comment by MSevey** [comment]
Thanks for the ticket @Delivator 

@meeh0w I assigned you in Linear, can you follow up on how the team wants to handle the discrepancy?

**Comment by interstella-5555** [comment]
We are in fact using KiB/MiB but consciously display KB/MB (which is in user favour anyway) since most users are not familiar with KiB/MiB and would be confused about what the "i" stands for. This is a common practice also used in aws and some other cloud storage providers. Related code: https://github.com/SkynetLabs/webportal-accounts-dashboard/blob/main/src/lib/humanBytes.js
